
#' Differential Methylation Analysis of Ribosomal DNA
#'
#' @description
#' Performs differential methylation analysis of ribosomal DNA (rDNA)
#' at either individual CpG sites or across rDNA regions. The function
#' acts as a wrapper for the site-level and region-level differential
#' methylation functions.
#'
#' Three regression models are supported: binomial logistic regression,
#' quasi-binomial logistic regression, and beta-binomial regression.
#' The latter two approaches account for overdispersion, which may
#' arise from biological variability and the repetitive nature of rDNA.
#'
#' @param meth_data A methylKit methylation object containing methylation
#'   data for the samples to be analysed.
#'
#' @param samples A vector specifying the experimental condition for
#'   each sample, in the same order as the samples in `meth_data`.
#'
#' @param species A character string specifying the reference genome
#'   used to identify rDNA regions (e.g., `"mm39"`).
#'
#' @param num_samples An integer specifying the number of samples
#'   included in the analysis.
#'
#' @param min_cov A positive integer specifying the minimum sequencing
#'   coverage required for a CpG site to be included in the analysis.
#'
#' @param region A character string specifying the rDNA region of
#'   interest for site-level analysis (e.g., `"18S"`, `"5.8S"`,
#'   `"28S"`, or `"45S"`).
#'
#' @param model_type A character string specifying the regression model:
#'   \describe{
#'     \item{`"binomial"`}{Binomial logistic regression fitted using
#'       `stats::glm()`.}
#'     \item{`"quasi-binomial"`}{Quasi-binomial logistic regression
#'       fitted using `stats::glm()`, allowing for overdispersion.}
#'     \item{`"beta-binomial"`}{Beta-binomial regression fitted using
#'       `glmmTMB::glmmTMB()`, accounting for overdispersion through
#'       a beta-binomial distribution.}
#'   }
#'
#' @param p_adjust_method A character string specifying the method
#'   used to adjust p-values for multiple testing. Use `"BH"` for
#'   the Benjamini-Hochberg false discovery rate correction.
#'
#' @param site Logical. If `TRUE` (default), differential methylation
#'   is performed independently at each CpG site within the specified
#'   rDNA region. If `FALSE`, region-level differential methylation
#'   analysis is performed.
#'
#' @details
#' The function first organises the methylation data into rDNA regions
#' using `sort_by_rDNA_region()`, applying the specified minimum
#' coverage threshold.
#'
#' When `site = TRUE`, methylation counts are extracted for individual
#' CpG sites within the selected region using `extract_site_data()`.
#' Differential methylation is then calculated using
#' `diff_meth_site()`.
#'
#' When `site = FALSE`, differential methylation is calculated across
#' rDNA regions using `analyze_methylation_regions()`. In this case,
#' the `region` argument is not passed to the analysis function.
#'
#' The selected regression model is used to assess differences in
#' methylation between experimental conditions. P-values are adjusted
#' using the specified multiple-testing correction method.
#'
#' @return
#' Returns the results of the selected differential methylation
#' analysis. For site-level analysis, the output contains results
#' for individual CpG positions, including regression coefficients,
#' odds ratios, p-values and adjusted p-values, where estimable.
#' For region-level analysis, the output contains the results
#' generated by `analyze_methylation_regions()`.
#' 
#' @examples
#' # Load the example mouse WGBS dataset
#' file_path <- system.file(
#'   "extdata",
#'   "filtered_meth_raw_chr1_chrRDNAm_small.rds",
#'   package = "myoRDNA",
#'   mustWork = TRUE
#' )
#'
#' loaded_data <- readRDS(file_path)
#'
#' # Define experimental conditions
#' # 0 = OLD, 1 = YOUNG
#' treatment <- c(
#'   0, 0, 0, 0, 0, 0,
#'   1, 1, 1, 1
#' )
#'
#' num_samples <- length(treatment)
#'
#' # Define sample groups
#' samples <- list(
#'   OLD = c(
#'     "SRR28431752", "SRR28431753", "SRR28431754",
#'     "SRR28431755", "SRR28431756", "SRR28431757"
#'   ),
#'   YOUNG = c(
#'     "SRR28431748", "SRR28431749",
#'     "SRR28431750", "SRR28431751"
#'   )
#' )
#'
#' # Construct a methylRawList object
#' loaded_data <- methods::new(
#'   "methylRawList",
#'   loaded_data,
#'   treatment = treatment
#' )
#'
#' # Extract rDNA methylation data
#' meth_rDNA <- get_rDNA_data(
#'   loaded_data,
#'   num_samples,
#'   rDNA_chr_name = "chrRDNAm"
#' )
#'
#' # Shift rDNA genomic coordinates
#' meth_rDNA_shifted <- shifting(
#'   meth_rdna_raw = meth_rDNA,
#'   cutoff = 35000,
#'   treatment = treatment
#' )
#'
#' # Site-level differential methylation analysis
#' site_results <- diff_meth(
#'   meth_data = meth_rDNA_shifted,
#'   samples = samples,
#'   species = "mm39",
#'   num_samples = num_samples,
#'   min_cov = 10,
#'   region = "18S",
#'   model_type = "binomial",
#'   p_adjust_method = "BH",
#'   site = TRUE
#' )
#'
#' head(site_results)
#'
#' # Region-level differential methylation analysis
#' region_results <- diff_meth(
#'   meth_data = meth_rDNA_shifted,
#'   samples = samples,
#'   species = "mm39",
#'   num_samples = num_samples,
#'   min_cov = 10,
#'   region = "18S",
#'   model_type = "binomial",
#'   p_adjust_method = "BH",
#'   site = FALSE
#' )
#'
#' head(region_results)
#'
#' @seealso
#' [sort_by_rDNA_region()],
#' [extract_site_data()],
#' [diff_meth_site()],
#' [analyze_methylation_regions()],
#' [stats::glm()],
#' [stats::p.adjust()],
#' [glmmTMB::glmmTMB()]
#'
#' @export
diff_meth <- function(
    meth_data,
    samples,
    species,
    num_samples,
    min_cov,
    region,
    model_type,
    p_adjust_method,
    site = TRUE) 
{
  region_res <- sort_by_rDNA_region(
    rDNA_meth_object=meth_data,
    num_samples=num_samples,
    species=species,
    min_cov=min_cov)
  if (site == TRUE)
  {
    all_data <- extract_site_data(
      region_res, 
      samples, 
      region)
    results <- diff_meth_site(
      all_data = all_data, 
      model_type = model_type, 
      p_adjust_method = p_adjust_method)
  } else {
    results <- analyze_methylation_regions(
      region_res = region_res,
      samples = samples,
      model_type = model_type,  
      p_adjust_method = p_adjust_method)
  }
  return(results)
}